# Codecov Configuration
# See: https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 70%  # 目标覆盖率
        threshold: 2%  # 允许下降2%
    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false

ignore:
  - "test/**/*"
  - "examples/**/*"
  - "scripts/**/*"
  - "reports/**/*"
  - "*.test.js"

